# Generated by Django 5.2.1 on 2025-10-06 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_cnic_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_room_owner',
            field=models.ForeignKey(blank=True, help_text='The show room owner who manages this user (for investors)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('investor', 'Investor'), ('show_room_owner', 'Show Room Owner'), ('admin', 'Admin')], default='investor', max_length=150),
        ),
    ]
