# Generated by Django 5.2.1 on 2025-10-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_show_room_owner_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload show room or related image', null=True, upload_to='show_room_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_room_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
