# Generated by Django 5.2.1 on 2025-09-25 04:50

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('brand', models.CharField(max_length=150)),
                ('model_name', models.CharField(max_length=150)),
                ('car_number', models.CharField(max_length=100, unique=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_type', models.CharField(default='petrol', max_length=150)),
                ('transmission', models.CharField(default='manual', max_length=150)),
                ('mileage', models.PositiveIntegerField(blank=True, help_text='Mileage in KM', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('admin_percentage', models.DecimalField(decimal_places=2, help_text='Admin commission percentage', max_digits=10)),
                ('status', models.CharField(default='available', max_length=150)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CarInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='show_room.car')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('car', 'investor')},
            },
        ),
    ]
