# Generated by Django 5.2.1 on 2025-09-25 05:45

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinvestment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='carinvestment',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carinvestment',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
