# Generated by Django 5.2.1 on 2025-09-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_room', '0002_remove_carinvestment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sold_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=80, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=80),
        ),
    ]
