# Generated by Django 5.2.1 on 2025-09-25 06:42

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_room', '0003_car_sold_amount_alter_car_total_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(help_text='Expense details like maintenance, repairs, etc.')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='show_room.car')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
