# Generated by Django 5.2.1 on 2025-09-29 11:12

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_room', '0004_carexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarExpenseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('image', models.ImageField(help_text='Upload expense receipt or related image', upload_to='expense_images/')),
                ('description', models.CharField(blank=True, help_text='Optional description for the image', max_length=255)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='show_room.carexpense')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
