# Generated by Django 5.2.1 on 2025-10-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_room', '0005_carexpenseimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
