# Generated by Django 5.2.1 on 2025-10-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_room', '0007_car_show_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='asking_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
