# Generated by Django 5.2.1 on 2025-10-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show_room', '0002_add_consignment_features'),
        ('show_room', '0008_car_asking_price'),
    ]

    operations = [
    ]
