# Generated by Django 5.2.1 on 2025-11-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_room', '0009_merge_20251007_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the car document', null=True, upload_to='car_document_image/'),
        ),
    ]
